[package]
name = "stt_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.6.0"
hound = "3.5.1"
num-traits = "0.2.18"
tokio = { version = "1.37.0", features = ["full"] }
